version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "4FL^xo9KVg%yF%F"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
    ports:
      - "1433:1433"
    container_name: sql
    volumes:
      - sql-data:/var/opt/mssql/

volumes:
  sql-data: